# BOARD_TYPE = deRFsam323M10-2

# global makefile var's (other makefiles use this)
CONTIKI_TARGET_MAIN = contiki-main.c
CONTIKI_TARGET_DIRS = .
CONTIKI_CPU_NAME = atsam3s4

# local makefile var's
CONTIKI_CPU = ${CONTIKI}/cpu/arm/$(CONTIKI_CPU_NAME)

include $(CONTIKI_CPU)/Makefile.$(CONTIKI_CPU_NAME)
